sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t limethecoder/so-much-flex-test -f ./Dockerfile.dev .client/

script:
    - docker run -e CI=true limethecoder/so-much-flex-test npm run test

after_success:
    - docker build -t limethecoder/so-much-flex-client .client/
    - docker build -t limethecoder/so-much-flex-server .server/
    - docker build -t limethecoder/so-much-flex-worker .worker/
    - docker build -t limethecoder/so-much-flex-nginx .nginx/

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push limethecoder/so-much-flex-client
    - docker push limethecoder/so-much-flex-server
    - docker push limethecoder/so-much-flex-worker
    - docker push limethecoder/so-much-flex-nginx